language: php

php:
  - 5.4
  - 5.5
  - hhvm

env:
  global:
    - secure: "Uft74EqqtZ2NOYECsx8bq8RaN8L40S12X9rFqsVLrbV2E8ru8ijL4mZNcRYYSSG5L6jR27wvlalTbzxBRWT1LnAt15AreCmuq/m9tj3yyXMNkX6dASVpw/qxTlgeAwGP26iFe4zgKubmyQXZroK8iIN4/HimRwYaADSeQ4j8QyQ="
    - secure: "UmFds85SDbGAGgayw75iXegyElb68BVjT+rwwaUDtokreSgUytnj6+puFcomYtE5SiHmhZbcDZs2f4jBh0GlmDCULBIsj2i3B+qUdt0S3k6yNUhqEM6FoEmrFeiD0hK3PUW267LJEhZjgQfjkAhRGoF6RpLQFrvZFi9ldbS207c="
    - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/sulu/logs
    - DB=mysql

before_script:
  - mkdir -p $LOGS_DIR
  - cp app/config/phpcr_doctrine_dbal.yml.dist app/config/phpcr.yml
  - cp app/Resources/templates/default.xml.dist app/Resources/templates/default.xml
  - cp app/Resources/templates/overview.xml.dist app/Resources/templates/overview.xml
  - cp app/Resources/webspaces/sulu.io.xml.dist app/Resources/webspaces/sulu.io.xml
  - ./tests/sauce/connect_setup.sh
  - composer self-update
  - composer update --prefer-dist --no-interaction
  - cp app/Resources/webspaces/sulu.io.xml.dist app/Resources/webspaces/sulu.io.xml
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --no-interaction
  - php app/console sulu:security:user:create admin Sulu Admin cmf@sulu.io en admin
  - php app/console server:run 0.0.0.0:8000 --router=../app/config/router_admin.php --env prod > /dev/null 2>&1 &
  - ./tests/sauce/connect_block.sh

script: bin/paratest -p 2 -f

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - ./tests/travis_print_logs.sh
