sulu_tag:
    resource: "@SuluTagBundle/Resources/config/routing.yml"
    prefix:   /admin/tag

sulu_tag_api:
    resource: "@SuluTagBundle/Resources/config/routing_api.yml"
    prefix:   /admin/api

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sulu_contact:
    resource: "@SuluContactBundle/Resources/config/routing.yml"
    prefix: /admin/contact

sulu_contact_api:
    type: rest
    resource: "@SuluContactBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.yml"
    prefix: /admin/security

sulu_security_api:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_content:
    resource: "@SuluContentBundle/Resources/config/routing.yml"
    prefix: /admin/content

sulu_content_api:
    type: rest
    resource: "@SuluContentBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing.yml"
    prefix: /admin/media

sulu_media_website:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_media_api:
    resource: "@SuluMediaBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_category:
    resource: "@SuluCategoryBundle/Resources/config/routing.yml"
    prefix: /admin/category

sulu_category_api:
    resource: "@SuluCategoryBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_translate:
    resource: "@SuluTranslateBundle/Resources/config/routing.yml"
    prefix: /admin/translate

sulu_translate_api:
    resource: "@SuluTranslateBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /admin/api

sulu_location:
    resource: "@SuluLocationBundle/Resources/config/routing.yml"
    prefix: /admin/location

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing.yml"
    prefix: /admin/website

# for preview
client_website:
    type: portal
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"
