imports:
    - { resource: parameters.yml }
    - { resource: phpcr.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    write_to:       "%kernel.root_dir%/../web"
    #bundles:        []
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: xml
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
        resolve_target_entities:
            Sulu\Component\Security\UserInterface: Sulu\Bundle\SecurityBundle\Entity\User
            Sulu\Bundle\ProductBundle\Entity\ProductInterface: Sulu\Bundle\ProductBundle\Entity\Product
            Sulu\Bundle\SecurityBundle\Entity\RoleInterface: Sulu\Bundle\SecurityBundle\Entity\Role

stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json

liip_theme:
    themes: ["default"]
    active_theme: "default"
    load_controllers: false

sulu_core:
    phpcr:
        backend:    %phpcr_backend%
        workspace:  %phpcr_workspace%
        username:   %phpcr_user%
        password:   %phpcr_pass%
    webspace:
        config_dir: %kernel.root_dir%/Resources/webspaces
    content:
        structure:
            default_type:
                snippet: default
                page: default
            paths:
                app_page:
                    path: "%kernel.root_dir%/Resources/pages"
                    internal: false
                    type: page
                app_snippet:
                    path: "%kernel.root_dir%/Resources/snippets"
                    internal: false
                    type: snippet
                sulu:
                    path: "%kernel.root_dir%/../vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Content/templates"
                    internal: true
                    type: page
    http_cache:
        ~

sulu_media:
    search:
        enabled: true
    ghost_script:
        path: %ghost_script_path%
    format_manager:
        response_headers: %format_manager.response_headers%
    format_cache:
        public_folder: %format_cache.public_folder%

cmf_core:
    publish_workflow:
        enabled: false
