imports:
    - { resource: parameters.yml }
    - { resource: phpcr.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    write_to:       "%kernel.root_dir%/../web"
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite:
            apply_to: '\.(css)$'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: "xml"
                prefix: "Gedmo\Tree\Entity"
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: "GedmoTree" # this one is optional and will default to the name set for the mapping
                is_bundle: false
        resolve_target_entities:
            Sulu\Bundle\MediaBundle\Entity\CollectionInterface: Sulu\Bundle\MediaBundle\Entity\Collection
            Sulu\Bundle\ContactBundle\Entity\AccountInterface: Sulu\Bundle\ContactBundle\Entity\Account

# Doctrine Extension Configuration
stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS REST Configuration
fos_rest:
    routing_loader:
        default_format: "json"

# LIIP Theme Configuration
liip_theme:
    themes: ["default"]
    active_theme: "default"
    load_controllers: false

# SULU Core Configuration
sulu_core:
    locales: ["de","en"]
    phpcr:
        backend:    "%phpcr_backend%"
        workspace:  "%phpcr_workspace%"
        username:   "%phpcr_user%"
        password:   "%phpcr_pass%"
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: %kernel.root_dir%/Resources/pages
                    type: home
                page:
                    path: "%kernel.root_dir%/Resources/pages"
                    type: "page"
                snippet:
                    path: "%kernel.root_dir%/Resources/snippets"
                    type: "snippet"
                sulu:
                    path: "%kernel.root_dir%/../vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Content/templates"
                    type: "page"

# SULU Media configuration
sulu_media:
    search:
        enabled: true

sulu_websocket:
    server:
        http_host: %websocket_url%
        port: %websocket_port%

# Symfony CMF Configuration
cmf_core:
    publish_workflow:
        enabled: false

sulu_http_cache:
    handlers:
        paths:
            enabled: true
        public:
            max_age: 240
            shared_max_age: 240
            use_page_ttl: true
            enabled: true
        debug:
            enabled: %kernel.debug%
    proxy_client:
        symfony:
            enabled: true

sulu_content:
    search:
        mapping:
            Sulu\Bundle\ContentBundle\Document\PageDocument:
                index: page
                category: page
            Sulu\Bundle\SnippetBundle\Document\SnippetDocument:
                index: snippet
                category: snippet

massive_search:
    localization_strategy: index
    persistence:
        doctrine_orm:
            enabled: true

doctrine_cache:
   providers:
       phpcr_meta:
           type: %phpcr_cache%
       phpcr_nodes:
           type: %phpcr_cache%

jms_serializer:
    metadata:
        debug: %kernel.debug%

sulu_document_manager:
    mapping:
        page:
            class: Sulu\Bundle\ContentBundle\Document\PageDocument
            phpcr_type: sulu:page
        home:
            class: Sulu\Bundle\ContentBundle\Document\HomeDocument
            phpcr_type: sulu:home
        route:
            class: Sulu\Bundle\ContentBundle\Document\RouteDocument
            phpcr_type: sulu:path
        snippet:
            class: Sulu\Bundle\SnippetBundle\Document\SnippetDocument
            phpcr_type: sulu:snippet
