imports:
    - { resource: phpcr.yml }

framework:
    translator: { fallback: "%locale%" }

assetic:
    write_to: "%kernel.root_dir%/../web"
    filters:
        cssrewrite:
            apply_to: "\\.(css)$"

doctrine:
    orm:
        mappings:
            gedmo_tree:
                type: "xml"
                prefix: "Gedmo\\Tree\\Entity"
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: "GedmoTree" # this one is optional and will default to the name set for the mapping
                is_bundle: false
        dql:
            string_functions:
                group_concat: Oro\ORM\Query\AST\Functions\String\GroupConcat
        resolve_target_entities:
            Sulu\Bundle\MediaBundle\Entity\CollectionInterface: Sulu\Bundle\MediaBundle\Entity\Collection
            Sulu\Bundle\ContactBundle\Entity\AccountInterface: Sulu\Bundle\ContactBundle\Entity\Account

# Doctrine cache providers
doctrine_cache:
    providers:
        phpcr_meta:
            type: "%phpcr_cache%"
        phpcr_nodes:
            type: "%phpcr_cache%"

# Doctrine Extension Configuration
stof_doctrine_extensions:
    orm:
        default:
            tree: true

# JMS Serializer
jms_serializer:
    metadata:
        debug: "%kernel.debug%"

# Symfony CMF Configuration
cmf_core:
    publish_workflow:
        enabled: false

# Massive Bundles
massive_search:
    metadata:
        prefix: sulu
    persistence:
        doctrine_orm:
            enabled: true

# Sulu Bundles
sulu_core:
    locales:
        de: Deutsch
        en: English
        fr: Fran√ßais
    fallback_locale: 'en'
    translations: ['de', 'en', 'fr']
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: "%kernel.root_dir%/Resources/pages"
                    type: "home"
                page:
                    path: "%kernel.root_dir%/Resources/pages"
                    type: "page"
                snippet:
                    path: "%kernel.root_dir%/Resources/snippets"
                    type: "snippet"
                sulu:
                    path: "%kernel.root_dir%/../vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Content/templates"
                    type: "page"
            type_map:
                page: "\\Sulu\\Component\\Content\\Compat\\Structure\\PageBridge"
                home: "\\Sulu\\Component\\Content\\Compat\\Structure\\PageBridge"
                snippet: "\\Sulu\\Component\\Content\\Compat\\Structure\\SnippetBridge"

sulu_media:
    search:
        enabled: true

sulu_websocket:
    server:
        http_host: "%websocket_url%"
        port: "%websocket_port%"

sulu_content:
    search:
        mapping:
            Sulu\Bundle\ContentBundle\Document\PageDocument:
                index: page
            Sulu\Bundle\SnippetBundle\Document\SnippetDocument:
                index: snippet

sulu_document_manager:
    sessions:
        default:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
        live:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%_live"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
    mapping:
        page:
            class: Sulu\Bundle\ContentBundle\Document\PageDocument
            phpcr_type: sulu:page
        home:
            class: Sulu\Bundle\ContentBundle\Document\HomeDocument
            phpcr_type: sulu:home
        route:
            class: Sulu\Bundle\ContentBundle\Document\RouteDocument
            phpcr_type: sulu:path
        snippet:
            class: Sulu\Bundle\SnippetBundle\Document\SnippetDocument
            phpcr_type: sulu:snippet

sulu_http_cache:
    handlers:
        paths:
            enabled: true
        public:
            max_age: 240
            shared_max_age: 240
            use_page_ttl: true
            enabled: true
        debug:
            enabled: %kernel.debug%
    proxy_client:
        symfony:
            enabled: true

dubture_f_fmpeg:
    ffmpeg_binary: /usr/local/bin/ffmpeg # path to ffmpeg
    ffprobe_binary: /usr/local/bin/ffprobe # path to ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: "@sulu_core.serialize_caching_strategy"
